services:
  mongo:
    image: mongo:4.4.26
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db
    container_name: mongo_db

volumes:
  mongo_data:

